export const FETCH_RANDOM_JOKE_LOADING = 'FETCH_RANDOM_JOKE_LOADING'

export const FETCH_RANDOM_JOKE_SUCCESS = 'FETCH_RANDOM_JOKE_SUCCESS'
export const FETCH_RANDOM_JOKE_FAILURE = 'FETCH_RANDOM_JOKE_FAILURE'

export const FETCH_RANDOM_JOKES_BY_CATEGORY_LOADING =
  'FETCH_RANDOM_JOKES_LOADING'
export const FETCH_RANDOM_JOKES_BY_CATEGORY_SUCCESS =
  'FETCH_RANDOM_JOKES_SUCCESS'
export const FETCH_RANDOM_JOKES_BY_CATEGORY_FAILURE =
  'FETCH_RANDOM_JOKES_FAILURE'

export const SEARCH_JOKES_LOADING = 'SEARCH_JOKES_LOADING'
export const SEARCH_JOKES_SUCCESS = 'SEARCH_JOKES_SUCCESS'
export const SEARCH_JOKES_FAILURE = 'SEARCH_JOKES_FAILURE'
