export const FETCH_ALL_CATEGORIES_LOADING = 'FETCH_ALL_CATEGORIES_LOADING'
export const FETCH_ALL_CATEGORIES_FAILURE = 'FETCH_ALL_CATEGORIES_FAILURE'
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS'

export const GET_JOKE_BY_CATEGORY_LOADING = 'GET_JOKE_BY_CATEGORY_LOADING'
export const GET_JOKE_BY_CATEGORY_FAILURE = 'GET_JOKE_BY_CATEGORY_FAILURE'
export const GET_JOKE_BY_CATEGORY_SUCCESS = 'GET_JOKE_BY_CATEGORY_SUCCESS'
